common: &common
  adapter: postgresql
  username: gregdaviet
  encoding: unicode
  pool: 5

development:
  <<: *common
  database: sample_app_development

test:
  <<: *common
  database: sample_app_test

production:
  <<: *common
  database: sample_app_production